// src/views/Hypocrisy.tsx
import AboutGame from "@/sections/AboutGame";
import ArtMusic from "@/sections/ArtMusic";
import CallToAction from "@/sections/CallToAction";
import Characters from "@/sections/Characters";
import Gameplay from "@/sections/Gameplay";
import Hero from "@/sections/Hero";
import JoinUs from "@/sections/JoinUs";
import Roadmap from "@/sections/Roadmap";
import Team from "@/sections/Team";
import Universe from "@/sections/Universe";

export default function Hypocrisy() {
  return (
    <div>
      <Hero />
      <AboutGame />
      <Gameplay />
      <Universe />
      <Characters />
      <ArtMusic />
      <Roadmap />
      <Team />
      <JoinUs />
      <CallToAction />
    </div>
  );
}

// src/views/Hypocrisy.svelte
<script lang="ts">
import AboutGame from "@/sections/AboutGame.svelte";
import ArtMusic from "@/sections/ArtMusic.svelte";
import CallToAction from "@/sections/CallToAction.svelte";
import Characters from "@/sections/Characters.svelte";
import Gameplay from "@/sections/Gameplay.svelte";
import Hero from "@/sections/Hero.svelte";
import JoinUs from "@/sections/JoinUs.svelte";
import Roadmap from "@/sections/Roadmap.svelte";
import Team from "@/sections/Team.svelte";
import Universe from "@/sections/Universe.svelte";
</script>

<div>
  <Hero />
  <AboutGame />
  <Gameplay />
  <Universe />
  <Characters />
  <ArtMusic />
  <Roadmap />
  <Team />
  <JoinUs />
  <CallToAction />
</div>
