// src/components/Navbar.svelte
<script lang="ts">
import { onMount } from "svelte";
import LanguageSwitcher from "@/components/LanguageSwitcher.svelte";
import { t } from "@/lib/i18n/t";
import { cn } from "@/lib/utils";
import { page } from "$app/stores";

let isGamePage = $derived($page.url.pathname.startsWith("/games/"));
let mobileOpen = $state(false);
let hidden = $state(false);
let lastScrollY = 0;

function closeMobile() {
  mobileOpen = false;
}

onMount(() => {
  function onScroll() {
    const y = window.scrollY;
    if (y < 52) hidden = false;
    else hidden = y > lastScrollY;
    lastScrollY = y;
  }
  window.addEventListener("scroll", onScroll, { passive: true });
  return () => window.removeEventListener("scroll", onScroll);
});
</script>

<nav
  class={cn(
    "fixed top-0 left-0 right-0 z-[500] flex items-center justify-between px-6 lg:px-16 h-[52px] backdrop-blur-sm transition-transform duration-300",
    hidden && !mobileOpen && "-translate-y-full",
    isGamePage
      ? "bg-[#050507]/80 border-b border-white/10"
      : "bg-white/[0.96] border-b-[1.5px] border-dark-950",
  )}
>
  <a
    href="/"
    class={cn(
      "font-display text-[1.4rem] tracking-[0.18em] transition-colors no-underline",
      isGamePage ? "text-white hover:text-gold" : "text-dark-950 hover:text-gold",
    )}
  >ATMA</a>

  <!-- Desktop nav -->
  <div class="hidden md:flex items-center gap-1">
    {#if isGamePage}
      <button type="button" class="font-mono text-[0.67rem] tracking-[0.1em] uppercase text-white/50 px-3.5 py-1.5 hover:text-white transition-colors no-underline bg-transparent border-none cursor-pointer" onclick={() => document.querySelector('#about')?.scrollIntoView({ behavior: 'smooth' })}>{t("nav.about")}</button>
      <button type="button" class="font-mono text-[0.67rem] tracking-[0.1em] uppercase text-white/50 px-3.5 py-1.5 hover:text-white transition-colors no-underline bg-transparent border-none cursor-pointer" onclick={() => document.querySelector('#join')?.scrollIntoView({ behavior: 'smooth' })}>{t("nav.join")}</button>
    {:else}
      <a href="/" class={cn("font-mono text-[0.67rem] tracking-[0.1em] uppercase px-3.5 py-1.5 transition-all no-underline", $page.url.pathname === '/' ? 'text-white bg-dark-950' : 'text-text hover:text-dark-950 hover:bg-surface')}>{t("nav.about")}</a>
      <a href="/games/hypocrisy" class={cn("font-mono text-[0.67rem] tracking-[0.1em] uppercase px-3.5 py-1.5 transition-all no-underline", $page.url.pathname.startsWith('/games') ? 'text-white bg-dark-950' : 'text-text hover:text-dark-950 hover:bg-surface')}>{t("nav.ourGames")}</a>
    {/if}
    <div class={isGamePage ? "[&_button]:text-white/50 [&_button]:hover:text-white [&_button.text-red]:text-red" : ""}>
      <LanguageSwitcher />
    </div>
    <button
      type="button"
      class="font-mono text-[0.67rem] tracking-[0.1em] uppercase text-white bg-red px-4 py-1.5 ml-3 hover:bg-[#9e1400] transition-colors cursor-pointer border-none"
      onclick={() => {
        window.dispatchEvent(new CustomEvent('scrollto', { detail: 'join' }));
      }}
    >{t("nav.getInTouch")} &darr;</button>
  </div>

  <!-- Mobile hamburger -->
  <button
    type="button"
    class={cn(
      "md:hidden flex flex-col justify-center gap-[5px] w-8 h-8 bg-transparent border-none cursor-pointer p-0",
    )}
    onclick={() => (mobileOpen = !mobileOpen)}
    aria-label="Toggle menu"
  >
    <span class={cn("block w-5 h-[1.5px] transition-all origin-center", isGamePage ? "bg-white" : "bg-dark-950", mobileOpen && "translate-y-[6.5px] rotate-45")}></span>
    <span class={cn("block w-5 h-[1.5px] transition-all", isGamePage ? "bg-white" : "bg-dark-950", mobileOpen && "opacity-0")}></span>
    <span class={cn("block w-5 h-[1.5px] transition-all origin-center", isGamePage ? "bg-white" : "bg-dark-950", mobileOpen && "-translate-y-[6.5px] -rotate-45")}></span>
  </button>
</nav>

<!-- Mobile menu overlay -->
{#if mobileOpen}
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div
    class={cn(
      "fixed inset-0 top-[52px] z-[499] md:hidden flex flex-col items-center pt-8 gap-4 backdrop-blur-md",
      isGamePage ? "bg-[#050507]/95" : "bg-white/95",
    )}
    onclick={closeMobile}
    onkeydown={(e) => { if (e.key === "Escape") closeMobile(); }}
  >
    {#if isGamePage}
      <button type="button" class="font-mono text-[0.8rem] tracking-[0.1em] uppercase text-white/70 px-4 py-2 hover:text-white transition-colors bg-transparent border-none cursor-pointer" onclick={() => { closeMobile(); document.querySelector('#about')?.scrollIntoView({ behavior: 'smooth' }); }}>{t("nav.about")}</button>
      <button type="button" class="font-mono text-[0.8rem] tracking-[0.1em] uppercase text-white/70 px-4 py-2 hover:text-white transition-colors bg-transparent border-none cursor-pointer" onclick={() => { closeMobile(); document.querySelector('#join')?.scrollIntoView({ behavior: 'smooth' }); }}>{t("nav.join")}</button>
    {:else}
      <a href="/" onclick={closeMobile} class={cn("font-mono text-[0.8rem] tracking-[0.1em] uppercase px-4 py-2 transition-all no-underline", $page.url.pathname === '/' ? 'text-white bg-dark-950' : 'text-text hover:text-dark-950')}>{t("nav.about")}</a>
      <a href="/games/hypocrisy" onclick={closeMobile} class={cn("font-mono text-[0.8rem] tracking-[0.1em] uppercase px-4 py-2 transition-all no-underline", $page.url.pathname.startsWith('/games') ? 'text-white bg-dark-950' : 'text-text hover:text-dark-950')}>{t("nav.ourGames")}</a>
    {/if}
    <div class={isGamePage ? "[&_button]:text-white/50 [&_button]:hover:text-white [&_button.text-red]:text-red" : ""}>
      <LanguageSwitcher />
    </div>
    <button
      type="button"
      class="font-mono text-[0.8rem] tracking-[0.1em] uppercase text-white bg-red px-6 py-2.5 mt-2 hover:bg-[#9e1400] transition-colors cursor-pointer border-none"
      onclick={() => {
        closeMobile();
        window.dispatchEvent(new CustomEvent('scrollto', { detail: 'join' }));
      }}
    >{t("nav.getInTouch")} &darr;</button>
  </div>
{/if}

// src/components/Navbar.tsx
"use client";

import { ChevronDown, Menu, X } from "lucide-react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import { cn } from "@/lib/utils";

const gamesSections = [
  { label: "About", id: "about" },
  { label: "Gameplay", id: "gameplay" },
  { label: "Universe", id: "universe" },
  { label: "Characters", id: "characters" },
  { label: "Art & Music", id: "art-music" },
  { label: "Roadmap", id: "roadmap" },
  { label: "Team", id: "team" },
];

export default function Navbar() {
  const [scrolled, setScrolled] = useState(false);
  const [mobileOpen, setMobileOpen] = useState(false);
  const [gamesOpen, setGamesOpen] = useState(false);
  const pathname = usePathname();
  const isHypocrisy = pathname === "/games/hypocrisy";

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 50);
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  const scrollToSection = (id: string) => {
    const el = document.getElementById(id);
    if (el) {
      el.scrollIntoView({ behavior: "smooth" });
      setMobileOpen(false);
    }
  };

  return (
    <nav
      className={cn(
        "fixed top-0 left-0 right-0 z-50 transition-all duration-300",
        scrolled ? "bg-dark-950/80 backdrop-blur-xl border-b border-white/5" : "bg-transparent",
      )}
    >
      <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
        {/* Logo */}
        <Link
          href="/"
          className="font-display text-xl font-semibold tracking-[0.2em] text-white hover:text-accent-400 transition-colors"
        >
          ATMA
        </Link>

        {/* Desktop Nav */}
        <div className="hidden md:flex items-center gap-8">
          {/* Games Dropdown */}
          {/* biome-ignore lint/a11y/noStaticElementInteractions: hover dropdown */}
          <div className="relative" onMouseEnter={() => setGamesOpen(true)} onMouseLeave={() => setGamesOpen(false)}>
            <button
              type="button"
              className="flex items-center gap-1 text-sm text-white/70 hover:text-white transition-colors"
            >
              Games <ChevronDown className="w-3 h-3" />
            </button>
            {gamesOpen && (
              <div className="absolute top-full left-0 mt-2 w-48 bg-dark-800/95 backdrop-blur-xl border border-white/10 rounded-lg py-2 shadow-2xl">
                <Link
                  href="/games/hypocrisy"
                  className="flex items-center gap-3 px-4 py-2 text-sm text-white/70 hover:text-white hover:bg-white/5 transition-colors"
                  onClick={() => setGamesOpen(false)}
                >
                  <img src="/assets/images/game-icon.jpeg" alt="" className="w-6 h-6 rounded" />
                  Hypocrisy
                </Link>
              </div>
            )}
          </div>

          {isHypocrisy &&
            gamesSections.map((s) => (
              <button
                key={s.id}
                type="button"
                onClick={() => scrollToSection(s.id)}
                className="text-sm text-white/50 hover:text-white transition-colors"
              >
                {s.label}
              </button>
            ))}

          {!isHypocrisy && (
            <>
              <Link href="/#about" className="text-sm text-white/70 hover:text-white transition-colors">
                About
              </Link>
              <Link href="/#contact" className="text-sm text-white/70 hover:text-white transition-colors">
                Contact
              </Link>
            </>
          )}
        </div>

        {/* Mobile Hamburger */}
        <button
          type="button"
          className="md:hidden text-white/70 hover:text-white"
          onClick={() => setMobileOpen(!mobileOpen)}
        >
          {mobileOpen ? <X className="w-6 h-6" /> : <Menu className="w-6 h-6" />}
        </button>
      </div>

      {/* Mobile Menu */}
      {mobileOpen && (
        <div className="md:hidden bg-dark-950/95 backdrop-blur-xl border-t border-white/5 px-6 py-4 space-y-3">
          <Link
            href="/games/hypocrisy"
            className="flex items-center gap-3 text-sm text-white/70 hover:text-white"
            onClick={() => setMobileOpen(false)}
          >
            <img src="/assets/images/game-icon.jpeg" alt="" className="w-6 h-6 rounded" />
            Hypocrisy
          </Link>
          {isHypocrisy &&
            gamesSections.map((s) => (
              <button
                key={s.id}
                type="button"
                onClick={() => scrollToSection(s.id)}
                className="block text-sm text-white/50 hover:text-white"
              >
                {s.label}
              </button>
            ))}
        </div>
      )}
    </nav>
  );
}
